---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cloud-pak-deployer
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cloud-pak-deployer
  namespace: cloud-pak-deployer
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cloud-pak-deployer
  namespace: cloud-pak-deployer
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/IBM/cloud-pak-deployer'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
  triggers:
    - type: "ConfigChange"
  output:
    to:
      kind: ImageStreamTag
      name: 'cloud-pak-deployer:latest'

