---
global_config:
  environment_name: sample
  cloud_platform: existing-ocp
  env_id: ocp-50f1njf3h5-1axg
  confirm_destroy: False

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.12
  cluster_name: "{{ env_id }}"
  domain_name: cloud.techzone.ibm.com
  openshift_storage:
  - storage_name: custom
    storage_type: custom
    ocp_storage_class_file: ocs-storagecluster-cephfs
    ocp_storage_class_block: ocs-storagecluster-ceph-rbd
