---
global_config:
  environment_name: cloudpak
  cloud_platform: existing-ocp
  env_id: ocp
  confirm_destroy: False

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.12
  cluster_name: PATCHED_BY_JOB
  domain_name: PATCHED_BY_JOB
  openshift_storage:
  - storage_name: custom
    storage_type: custom
    ocp_storage_class_file: ocs-storagecluster-cephfs
    ocp_storage_class_block: ocs-storagecluster-ceph-rbd
